### ISSUE TITLE
Implement "Nesting Depth" lint rule

### ISSUE THREAD

**Issue by srawlins** [sass/linter#11]
Need to implement a lint rule that reports style rules that are too deep, in terms of Sass nesting (not selector specificity):

```scss
p.foo {
  .bar {
    .error {
      .severe { // LINT
        color: red;
      }
    }
  }
}
```

This is similar to scss-lint's [NestingDepth](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#nestingdepth).
