### ISSUE TITLE
Add a lint for using @each with maps properly

### ISSUE THREAD

**Issue by nex3** [sass/linter#33]
A pattern I see occasionally is:

```scss
@each $key in map-keys($map) {
  $value: map-get($map, $key);
  // ...
}
```

This is an unnecessarily verbose way of writing:

```scss
@each $key, $value in $map {
  // ...
}
```

There are also some legitimate cases where only the key is used, so maybe it's a good idea to look for the pattern `map-get($map, $key)` in the loop body before raising the lint?
